name: speakeasy
description: Open source version of tabu
version: 1.4.6+21

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  csv: 5.0.1
  flutter_launcher_icons: 0.13.1
  equatable: 2.0.0
  flutter_riverpod: 0.14.0+3
  soundpool: 2.3.0
  url_launcher: 6.1.6
  get: 4.6.5
  blinking_text: 1.0.2
  vibration: 1.7.6
  auto_size_text: 3.0.0
  wakelock: 0.6.2
  google_fonts: 3.0.1
  simple_animations: 5.0.0+2
  page_transition: 2.0.9
  fluttertoast: 8.2.1
  easy_localization: 3.0.1
  in_app_review: 2.0.4
  shared_preferences: 2.0.15
  flutter_svg: 1.1.5
  package_info: 2.0.2
  in_app_purchase: 3.0.8
  locale_emoji: ^0.2.1
  flutter_localized_locales: ^2.0.4
  restart_app: ^1.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  #android: "launcher_icon"
  ios: true
  android: true
  remove_alpha_ios: true
  image_path: "assets/icons/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/words/it/
    - assets/words/en/
    - assets/sounds/
    - assets/icons/
    - assets/lang/

  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Black.otf