name: opentabu
description: Open source version of tabu
version: 1.2.0+5

environment:
  sdk: ">=2.5.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  csv: 5.0.0
  flutter_launcher_icons: 0.9.0
  equatable: 2.0.0
  flutter_riverpod: 0.14.0+3
  soundpool: 2.0.0-nullsafety.0
  url_launcher: 6.0.3
  get: 4.1.4
  blinking_text: 1.0.1+2
  vibration: 1.7.3
  auto_size_text: 2.1.0
  wakelock: 0.5.1
  google_fonts: 2.0.0
  simple_animations: 3.1.1
  page_transition: 2.0.2
  fluttertoast: 8.0.6
  easy_localization: 3.0.0
  in_app_review: 2.0.2
  shared_preferences: 2.0.5
  flutter_svg: 0.22.0
  package_info: 2.0.0
  in_app_purchase: 0.5.2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  #android: "launcher_icon"
  ios: true
  android: true
  image_path: "assets/icons/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/csv/words.csv
    - assets/sounds/
    - assets/icons/
    - assets/lang/

  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Black.otf