name: opentabu
description: Open source version of tabu
version: 1.0.1+2

environment:
  sdk: ">=2.5.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  csv: ^4.1.0
  flutter_launcher_icons: ^0.8.1
  equatable: 1.1.1
  flutter_riverpod: 0.12.2
  soundpool: 1.1.3
  url_launcher: 5.7.10
  get: ^3.24.0
  blinking_text: ^0.0.4+1
  vibration: ^1.7.3
  auto_size_text: ^2.1.0
  wakelock: ^0.2.1+1
  google_fonts: ^1.1.1
  simple_animations: ^2.5.0
  page_transition: 1.1.7+6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  #android: "launcher_icon"
  ios: true
  android: true
  image_path: "assets/icons/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/csv/words.csv
    - assets/sounds/
    - assets/icons/
  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Black.otf