name: opentabu
description: The open source version of the most famous words game

dependencies:
  flutter:
    sdk: flutter

  csv: "^3.1.2"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
   - csv/words.csv