name: Tabu
description: The open source version of the most famous words game

dependencies:
  flutter:
    sdk: flutter

  csv: "^3.1.2"
  flutter_launcher_icons: "^0.5.2"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
   - csv/words.csv


flutter_icons:
  android: true
  image_path: "assets/icon/web_hi_res_512.png"