name: opentabu
description: Open version of tabu
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  csv: ^4.0.3
  flutter_launcher_icons: ^0.7.4
  after_layout: ^1.0.7+2
  flutter_bloc: 3.2.0
  equatable: 1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - csv/words.csv